include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore   # suppresses freezed warnings
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    prefer_final_locals: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_relative_imports: false
    unawaited_futures: true
