import 'dart:convert';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:vitalpet/core/audit/audit_log_dao.dart';
import 'package:vitalpet/core/database/app_database.dart';
import 'package:vitalpet/core/database/dao_providers.dart';
import 'package:vitalpet/features/handoff/chart_data_builder.dart';
import 'package:vitalpet/features/handoff/handoff_providers.dart';
import 'package:vitalpet/features/handoff/narrative_context.dart';
import 'package:vitalpet/features/health/health_adapter.dart';
import 'package:vitalpet/features/slm/narrative_generator.dart';

// ── Constants ─────────────────────────────────────────────────────────────────

const String _kDisclaimer =
    'This summary was generated by VitalPet and is not a medical record. '
    'Please discuss with your clinician.';

// Brand colours (replicated as PDF colours — not Flutter Color, no dependency)
const _kPrimary = PdfColor.fromInt(0xFF0D7377);
const _kPrimaryLight = PdfColor.fromInt(0xFF3ABFC3);
const _kDanger = PdfColor.fromInt(0xFFE53935);
const _kWarning = PdfColor.fromInt(0xFFFFB300);
const _kSuccess = PdfColor.fromInt(0xFF43A047);
const _kGrey100 = PdfColor.fromInt(0xFFF5F7FA);
const _kGrey300 = PdfColor.fromInt(0xFFE0E0E0);
const _kGrey600 = PdfColor.fromInt(0xFF6B7280);
const _kTextPrimary = PdfColor.fromInt(0xFF1A1D23);

// ── Generator ─────────────────────────────────────────────────────────────────

/// Generates the doctor handoff PDF and shares it via the native share sheet.
/// Pure Dart — no native bridge required.
/// Writes [AuditEvent.handoffExport] before sharing.
class HandoffGenerator {
  const HandoffGenerator();

  /// Full pipeline:
  /// 1. Load check-ins from DB for the last [dayCount] days
  /// 2. Build de-identified [NarrativeContext]
  /// 3. Generate clinical narrative (rule-based or SLM)
  /// 4. Build pw.Document with up to 3 pages
  /// 5. Write HANDOFF_EXPORT audit entry
  /// 6. Share via native share sheet — VitalPet never observes the destination
  Future<void> generateAndShare({
    required int dayCount,
    required WidgetRef ref,
  }) async {
    final now = DateTime.now().toUtc();
    final endDay = DateTime(now.year, now.month, now.day);
    final startDay = endDay.subtract(Duration(days: dayCount - 1));
    final startStr = _fmt(startDay);
    final endStr = _fmt(endDay);

    // 1. Load check-ins
    final checkIns = await ref
        .read(checkInDaoProvider)
        .findByDateRange(startStr, endStr);

    // 2. Optional health data
    final healthAdapter = const HealthAdapter();
    final healthSnapshot = await healthAdapter.fetchSummary(
      start: startDay,
      end: endDay,
    );

    // 3. Build chart data
    final trendPoints =
        ChartDataBuilder.buildTrendChart(checkIns, startDay, endDay);
    final heatmap = ChartDataBuilder.buildHeatmap(checkIns);
    final symptomFreq = ChartDataBuilder.buildSymptomFrequency(checkIns);
    final notableEvents = ChartDataBuilder.buildNotableEvents(trendPoints);

    // 4. Aggregate stats (de-identified)
    final completed = checkIns.where((c) => !c.isPartial).length;
    final avgWellness = checkIns.isEmpty
        ? 0.0
        : checkIns
                .map((c) => c.overallStatus == 'great' ? 8.0 : 3.0)
                .reduce((a, b) => a + b) /
            checkIns.length;
    final trend = _computeTrend(trendPoints);
    final sortedDomains = (symptomFreq.entries.toList()
          ..sort((a, b) => b.value.compareTo(a.value)))
        .map((e) => e.key)
        .toList();

    final narrativeCtx = NarrativeContext(
      dayCount: dayCount,
      averageWellnessScore: avgWellness,
      dominantSymptomDomains: sortedDomains.take(3).toList(),
      deviationAlertSummaries: notableEvents
          .take(5)
          .map((e) =>
              '${DateFormat('MMM d').format(e.date)}: ${e.reason}')
          .toList(),
      trendDirection: trend,
      symptomFrequency: symptomFreq,
      mostFrequentPainRegions: _extractPainRegions(checkIns),
      fatigueBlockedDailyCount: _countFatigueBlocked(checkIns),
      totalCheckins: dayCount,
      completedCheckins: completed,
      healthCorrelationSummary: healthSnapshot != null
          ? [
              healthSnapshot.sleepVsBaselineSummary,
              healthSnapshot.stepsVsBaselineSummary,
            ].whereType<String>().join('; ')
          : null,
    );

    // 5. Generate narrative
    final narrative =
        await ref.read(narrativeGeneratorProvider).generate(narrativeCtx);

    // 6. Build PDF
    final pdf = pw.Document(
      title: 'VitalPet Health Summary',
      author: 'VitalPet',
      subject: 'Wellness Report',
    );

    pdf.addPage(_buildPage1(
      ctx: narrativeCtx,
      narrative: narrative,
      trendPoints: trendPoints,
      sortedDomains: sortedDomains,
      symptomFreq: symptomFreq,
      completed: completed,
      avgWellness: avgWellness,
      startStr: startStr,
      endStr: endStr,
    ));

    pdf.addPage(_buildPage2(
      heatmap: heatmap,
      notableEvents: notableEvents,
      startDay: startDay,
      trendPoints: trendPoints,
    ));

    if (healthSnapshot != null) {
      pdf.addPage(_buildPage3(
        healthSnapshot: healthSnapshot,
        trendPoints: trendPoints,
      ));
    }

    // 7. Write audit entry BEFORE sharing (never log the destination)
    final dateRangeStr = '$startStr/$endStr';
    final payloadHash =
        sha256.convert(utf8.encode(dateRangeStr)).toString();
    await ref
        .read(auditLogDaoProvider)
        .append(AuditEvent.handoffExport(payloadHash: payloadHash));

    // 8. Share via native share sheet (printing package — pure Dart)
    final bytes = Uint8List.fromList(await pdf.save());
    await Printing.sharePdf(
      bytes: bytes,
      filename:
          'vitalpet_summary_${DateFormat('yyyyMMdd').format(DateTime.now())}.pdf',
    );
  }

  // ── Page 1: Summary ───────────────────────────────────────────────────────

  pw.Page _buildPage1({
    required NarrativeContext ctx,
    required HandoffNarrative narrative,
    required List<TrendPoint> trendPoints,
    required List<String> sortedDomains,
    required Map<String, int> symptomFreq,
    required int completed,
    required double avgWellness,
    required String startStr,
    required String endStr,
  }) {
    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.symmetric(horizontal: 40, vertical: 32),
      build: (pw.Context context) {
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _pageHeader(startStr: startStr, endStr: endStr),
            pw.SizedBox(height: 16),
            _narrativeBlock(narrative),
            pw.SizedBox(height: 14),
            _summaryStatsRow(
              completed: completed,
              dayCount: ctx.dayCount,
              avgWellness: avgWellness,
              trend: ctx.trendDirection ?? 'stable',
            ),
            pw.SizedBox(height: 14),
            _sectionTitle('Top Symptom Categories'),
            pw.SizedBox(height: 6),
            _symptomFreqBar(sortedDomains, symptomFreq),
            pw.SizedBox(height: 14),
            _sectionTitle('Wellness Trend'),
            pw.SizedBox(height: 6),
            _trendChart(trendPoints),
            pw.Expanded(child: pw.SizedBox()),
            _footerBar(),
          ],
        );
      },
    );
  }

  // ── Page 2: Symptom Chronicle ─────────────────────────────────────────────

  pw.Page _buildPage2({
    required Map<String, int?> heatmap,
    required List<NotableEvent> notableEvents,
    required DateTime startDay,
    required List<TrendPoint> trendPoints,
  }) {
    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.symmetric(horizontal: 40, vertical: 32),
      build: (pw.Context context) {
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _pageHeader2(),
            pw.SizedBox(height: 16),
            _sectionTitle('6-Week Wellness Heatmap'),
            pw.SizedBox(height: 4),
            _heatmapLegend(),
            pw.SizedBox(height: 6),
            _calendarHeatmap(heatmap),
            pw.SizedBox(height: 16),
            _sectionTitle('Notable Events'),
            pw.SizedBox(height: 6),
            _notableEventsList(notableEvents),
            pw.Expanded(child: pw.SizedBox()),
            _footerBar(),
          ],
        );
      },
    );
  }

  // ── Page 3: Health Correlation (conditional) ──────────────────────────────

  pw.Page _buildPage3({
    required HealthSnapshot healthSnapshot,
    required List<TrendPoint> trendPoints,
  }) {
    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.symmetric(horizontal: 40, vertical: 32),
      build: (pw.Context context) {
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _pageHeader3(),
            pw.SizedBox(height: 16),
            _sectionTitle('Health Data Correlation'),
            pw.SizedBox(height: 8),
            _healthSummaryBlock(healthSnapshot),
            pw.SizedBox(height: 14),
            if (healthSnapshot.sleepVsBaselineSummary != null) ...[
              _sectionTitle('Sleep vs Wellness'),
              pw.SizedBox(height: 6),
              _healthCorrelationChart(trendPoints, label: 'Sleep deviation'),
              pw.SizedBox(height: 14),
            ],
            if (healthSnapshot.stepsVsBaselineSummary != null) ...[
              _sectionTitle('Activity vs Wellness'),
              pw.SizedBox(height: 6),
              _healthCorrelationChart(trendPoints, label: 'Step count deviation'),
            ],
            pw.Expanded(child: pw.SizedBox()),
            _footerBar(),
          ],
        );
      },
    );
  }

  // ── Widget builders ───────────────────────────────────────────────────────

  pw.Widget _pageHeader({required String startStr, required String endStr}) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'VitalPet Health Summary',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                color: _kPrimary,
              ),
            ),
            pw.Text(
              'Page 1 of 2–3',
              style: pw.TextStyle(fontSize: 8, color: _kGrey600),
            ),
          ],
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          'Period: $startStr → $endStr  ·  Generated: ${DateFormat('dd MMM yyyy').format(DateTime.now())}',
          style: pw.TextStyle(fontSize: 9, color: _kGrey600),
        ),
        pw.SizedBox(height: 8),
        pw.Divider(color: _kPrimary, thickness: 1.5),
      ],
    );
  }

  pw.Widget _pageHeader2() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'VitalPet — Symptom Chronicle',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                color: _kPrimary,
              ),
            ),
            pw.Text('Page 2', style: pw.TextStyle(fontSize: 8, color: _kGrey600)),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Divider(color: _kPrimary, thickness: 1.5),
      ],
    );
  }

  pw.Widget _pageHeader3() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'VitalPet — Health Correlation',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                color: _kPrimary,
              ),
            ),
            pw.Text('Page 3', style: pw.TextStyle(fontSize: 8, color: _kGrey600)),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Divider(color: _kPrimary, thickness: 1.5),
      ],
    );
  }

  pw.Widget _narrativeBlock(HandoffNarrative narrative) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: _kGrey100,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
        border: pw.Border.all(color: _kPrimaryLight, width: 0.5),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            narrative.headline,
            style: pw.TextStyle(
              fontSize: 13,
              fontWeight: pw.FontWeight.bold,
              color: _kTextPrimary,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            narrative.context,
            style: pw.TextStyle(fontSize: 9.5, color: _kTextPrimary, lineSpacing: 2),
          ),
          if (narrative.questions.isNotEmpty) ...[
            pw.SizedBox(height: 8),
            pw.Text(
              'Questions to raise:',
              style: pw.TextStyle(
                fontSize: 9.5,
                fontWeight: pw.FontWeight.bold,
                color: _kTextPrimary,
              ),
            ),
            pw.SizedBox(height: 4),
            ...narrative.questions.map(
              (q) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 3),
                child: pw.Row(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('• ', style: pw.TextStyle(fontSize: 9.5, color: _kPrimary)),
                    pw.Expanded(
                      child: pw.Text(
                        q,
                        style: pw.TextStyle(fontSize: 9.5, color: _kTextPrimary, lineSpacing: 1.5),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  pw.Widget _summaryStatsRow({
    required int completed,
    required int dayCount,
    required double avgWellness,
    required String trend,
  }) {
    final completionPct = dayCount > 0 ? ((completed / dayCount) * 100).round() : 0;
    return pw.Row(
      children: [
        _statBox('Check-ins', '$completed/$dayCount\n($completionPct%)'),
        pw.SizedBox(width: 8),
        _statBox('Avg Wellness', '${avgWellness.toStringAsFixed(1)}/10'),
        pw.SizedBox(width: 8),
        _statBox(
          'Trend',
          _capitalize(trend),
          boxColor: trend == 'improving'
              ? _kSuccess
              : trend == 'declining'
                  ? _kDanger
                  : _kWarning,
        ),
      ],
    );
  }

  pw.Widget _statBox(String label, String value, {PdfColor? boxColor}) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(10),
        decoration: pw.BoxDecoration(
          color: boxColor != null
              ? PdfColor(boxColor.red, boxColor.green, boxColor.blue, 0.12)
              : _kGrey100,
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
          border: pw.Border.all(
            color: boxColor ?? _kGrey300,
            width: 0.5,
          ),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(label,
                style: pw.TextStyle(fontSize: 8, color: _kGrey600)),
            pw.SizedBox(height: 4),
            pw.Text(value,
                style: pw.TextStyle(
                  fontSize: 12,
                  fontWeight: pw.FontWeight.bold,
                  color: boxColor ?? _kTextPrimary,
                )),
          ],
        ),
      ),
    );
  }

  pw.Widget _sectionTitle(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(
        fontSize: 11,
        fontWeight: pw.FontWeight.bold,
        color: _kPrimary,
      ),
    );
  }

  pw.Widget _symptomFreqBar(
    List<String> sortedDomains,
    Map<String, int> symptomFreq,
  ) {
    if (sortedDomains.isEmpty) {
      return pw.Text(
        'No symptoms recorded in this period.',
        style: pw.TextStyle(fontSize: 9, color: _kGrey600),
      );
    }
    final maxCount = symptomFreq.values.reduce((a, b) => a > b ? a : b);
    final top = sortedDomains.take(5).toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: top.map((domain) {
        final count = symptomFreq[domain] ?? 0;
        final fraction = maxCount > 0 ? count / maxCount : 0.0;
        return pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 4),
          child: pw.Row(
            children: [
              pw.SizedBox(
                width: 60,
                child: pw.Text(
                  _formatCategory(domain),
                  style: pw.TextStyle(fontSize: 8.5, color: _kTextPrimary),
                ),
              ),
              pw.SizedBox(
                width: 200,
                child: pw.Row(
                  children: [
                    pw.Container(
                      width: 200 * fraction,
                      height: 10,
                      decoration: const pw.BoxDecoration(
                        color: _kPrimary,
                        borderRadius:
                            pw.BorderRadius.all(pw.Radius.circular(3)),
                      ),
                    ),
                    pw.Container(
                      width: 200 * (1 - fraction),
                      height: 10,
                      decoration: const pw.BoxDecoration(
                        color: _kGrey300,
                        borderRadius:
                            pw.BorderRadius.all(pw.Radius.circular(3)),
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(width: 6),
              pw.Text(
                '$count sessions',
                style: pw.TextStyle(fontSize: 8, color: _kGrey600),
              ),
            ],
          ),
        );
      }).toList(),
    );
  }

  pw.Widget _trendChart(List<TrendPoint> points) {
    // Sample to at most 30 points for clarity on the chart
    final sampledPoints = _samplePoints(points, maxCount: 30);
    final hasData = sampledPoints.any((p) => p.score != null);

    if (!hasData) {
      return pw.Container(
        height: 80,
        alignment: pw.Alignment.center,
        child: pw.Text(
          'No wellness data in this period.',
          style: pw.TextStyle(fontSize: 9, color: _kGrey600),
        ),
      );
    }

    final indexedPoints = sampledPoints.asMap().entries.toList();
    final chartData = indexedPoints
        .where((e) => e.value.score != null)
        .map((e) => pw.PointChartValue(
              e.key.toDouble(),
              e.value.score!.toDouble(),
            ))
        .toList();

    return pw.SizedBox(
      height: 100,
      child: pw.Chart(
        grid: pw.CartesianGrid(
          xAxis: pw.FixedAxis<int>(
            List<int>.generate(sampledPoints.length, (i) => i),
            divisions: false,
            color: _kGrey300,
          ),
          yAxis: pw.FixedAxis<int>(
            const [0, 2, 4, 6, 8, 10],
            format: (v) => '$v',
            divisions: true,
            divisionsColor: _kGrey300,
          ),
        ),
        datasets: [
          pw.LineDataSet(
            legend: 'Wellness (1–10)',
            drawSurface: true,
            isCurved: true,
            color: _kPrimary,
            data: chartData,
          ),
        ],
      ),
    );
  }

  pw.Widget _calendarHeatmap(Map<String, int?> heatmap) {
    final now = DateTime.now();
    // Build 42 cells: 6 weeks × 7 days, oldest→newest left-to-right, top→bottom
    final cells = <MapEntry<DateTime, int?>>[];
    for (var i = 41; i >= 0; i--) {
      final date = DateTime(now.year, now.month, now.day)
          .subtract(Duration(days: i));
      final key = _fmt(date);
      cells.add(MapEntry(date, heatmap[key]));
    }

    final dayLabels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        // Day-of-week header
        pw.Row(
          children: dayLabels
              .map((d) => pw.Expanded(
                    child: pw.Text(
                      d,
                      style: pw.TextStyle(fontSize: 6.5, color: _kGrey600),
                      textAlign: pw.TextAlign.center,
                    ),
                  ))
              .toList(),
        ),
        pw.SizedBox(height: 3),
        // 6 weeks of cells
        for (var week = 0; week < 6; week++)
          pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 2),
            child: pw.Row(
              children: [
                for (var day = 0; day < 7; day++)
                  pw.Expanded(
                    child: pw.Container(
                      height: 14,
                      margin: const pw.EdgeInsets.symmetric(horizontal: 1),
                      decoration: pw.BoxDecoration(
                        color: _scoreToHeatColor(
                            cells[week * 7 + day].value),
                        borderRadius:
                            const pw.BorderRadius.all(pw.Radius.circular(2)),
                      ),
                    ),
                  ),
              ],
            ),
          ),
      ],
    );
  }

  pw.Widget _heatmapLegend() {
    return pw.Row(
      mainAxisSize: pw.MainAxisSize.min,
      children: [
        pw.Text('Less  ', style: pw.TextStyle(fontSize: 7, color: _kGrey600)),
        ...[_kGrey300, _kDanger, _kWarning, _kPrimaryLight, _kSuccess]
            .map((c) => pw.Container(
                  width: 10,
                  height: 10,
                  margin: const pw.EdgeInsets.symmetric(horizontal: 1),
                  decoration: pw.BoxDecoration(
                    color: c,
                    borderRadius:
                        const pw.BorderRadius.all(pw.Radius.circular(2)),
                  ),
                )),
        pw.Text('  More', style: pw.TextStyle(fontSize: 7, color: _kGrey600)),
        pw.SizedBox(width: 12),
        pw.Container(
          width: 10,
          height: 10,
          margin: const pw.EdgeInsets.symmetric(horizontal: 1),
          decoration: pw.BoxDecoration(
            color: _kGrey300,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(2)),
          ),
        ),
        pw.Text(' No data', style: pw.TextStyle(fontSize: 7, color: _kGrey600)),
      ],
    );
  }

  pw.Widget _notableEventsList(List<NotableEvent> events) {
    if (events.isEmpty) {
      return pw.Text(
        'No notable events in this period. Wellness remained above 4/10 with no fever or multi-category days.',
        style: pw.TextStyle(fontSize: 9, color: _kGrey600),
      );
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: events.take(10).map((event) {
        final scoreColor = event.score != null && event.score! <= 3
            ? _kDanger
            : _kWarning;
        return pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 5),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                width: 64,
                padding: const pw.EdgeInsets.symmetric(
                    horizontal: 4, vertical: 2),
                decoration: pw.BoxDecoration(
                  color: scoreColor,
                  borderRadius:
                      const pw.BorderRadius.all(pw.Radius.circular(3)),
                ),
                child: pw.Text(
                  DateFormat('MMM d').format(event.date),
                  style: pw.TextStyle(
                      fontSize: 8,
                      color: PdfColors.white,
                      fontWeight: pw.FontWeight.bold),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.SizedBox(width: 8),
              pw.Expanded(
                child: pw.Text(
                  event.reason,
                  style: pw.TextStyle(fontSize: 9, color: _kTextPrimary),
                ),
              ),
            ],
          ),
        );
      }).toList(),
    );
  }

  pw.Widget _healthSummaryBlock(HealthSnapshot snapshot) {
    final items = <String, String?>{
      'Sleep vs baseline': snapshot.sleepVsBaselineSummary,
      'Steps vs baseline': snapshot.stepsVsBaselineSummary,
      'Heart rate vs baseline': snapshot.hrVsBaselineSummary,
    };

    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: _kGrey100,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
        border: pw.Border.all(color: _kGrey300, width: 0.5),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: items.entries
            .where((e) => e.value != null)
            .map((e) => pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 4),
                  child: pw.Row(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.SizedBox(
                        width: 130,
                        child: pw.Text(
                          e.key,
                          style: pw.TextStyle(
                              fontSize: 9,
                              color: _kGrey600,
                              fontWeight: pw.FontWeight.bold),
                        ),
                      ),
                      pw.Expanded(
                        child: pw.Text(
                          e.value!,
                          style: pw.TextStyle(fontSize: 9, color: _kTextPrimary),
                        ),
                      ),
                    ],
                  ),
                ))
            .toList(),
      ),
    );
  }

  pw.Widget _healthCorrelationChart(
    List<TrendPoint> points, {
    required String label,
  }) {
    final hasData = points.any((p) => p.score != null);
    if (!hasData) {
      return pw.Container(
        height: 60,
        alignment: pw.Alignment.center,
        child: pw.Text(
          'Insufficient data to display $label chart.',
          style: pw.TextStyle(fontSize: 9, color: _kGrey600),
        ),
      );
    }

    final indexedPoints = points.asMap().entries.toList();
    final chartData = indexedPoints
        .where((e) => e.value.score != null)
        .map((e) => pw.PointChartValue(
              e.key.toDouble(),
              e.value.score!.toDouble(),
            ))
        .toList();

    return pw.SizedBox(
      height: 80,
      child: pw.Chart(
        grid: pw.CartesianGrid(
          xAxis: pw.FixedAxis<int>(
            List<int>.generate(points.length, (i) => i),
            divisions: false,
            color: _kGrey300,
          ),
          yAxis: pw.FixedAxis<int>(
            const [0, 2, 4, 6, 8, 10],
            format: (v) => '$v',
            divisions: true,
            divisionsColor: _kGrey300,
          ),
        ),
        datasets: [
          pw.LineDataSet(
            legend: label,
            drawSurface: false,
            isCurved: true,
            color: _kPrimary,
            data: chartData,
          ),
        ],
      ),
    );
  }

  /// Non-removable disclaimer footer — required on every page.
  pw.Widget _footerBar() {
    return pw.Column(
      children: [
        pw.Divider(color: _kGrey300, thickness: 0.5),
        pw.SizedBox(height: 4),
        pw.Text(
          _kDisclaimer,
          style: pw.TextStyle(
            fontSize: 7.5,
            color: _kGrey600,
            fontStyle: pw.FontStyle.italic,
          ),
          textAlign: pw.TextAlign.center,
        ),
      ],
    );
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  static String _fmt(DateTime d) =>
      '${d.year.toString().padLeft(4, '0')}-'
      '${d.month.toString().padLeft(2, '0')}-'
      '${d.day.toString().padLeft(2, '0')}';

  /// Computes trend direction from the first and last halves of trend scores.
  static String _computeTrend(List<TrendPoint> points) {
    final scored = points.where((p) => p.score != null).toList();
    if (scored.length < 4) return 'stable';

    final half = scored.length ~/ 2;
    final firstHalfAvg =
        scored.take(half).map((p) => p.score!).reduce((a, b) => a + b) / half;
    final secondHalfAvg = scored
            .skip(half)
            .map((p) => p.score!)
            .reduce((a, b) => a + b) /
        (scored.length - half);

    final delta = secondHalfAvg - firstHalfAvg;
    if (delta > 0.75) return 'improving';
    if (delta < -0.75) return 'declining';
    return 'stable';
  }

  static List<String> _extractPainRegions(List<CheckIn> checkIns) {
    final regionCount = <String, int>{};
    for (final ci in checkIns) {
      final answers = _parseAnswers(ci.answersJson);
      final symptoms = (answers['symptoms'] as List<dynamic>?) ?? [];
      for (final s in symptoms) {
        final sMap = s as Map<String, dynamic>;
        if (sMap['category'] != 'pain') continue;
        final regions = (sMap['regions'] as List<dynamic>?) ?? [];
        for (final r in regions) {
          final region = r as String?;
          if (region != null) {
            regionCount[region] = (regionCount[region] ?? 0) + 1;
          }
        }
      }
    }
    return (regionCount.entries.toList()
          ..sort((a, b) => b.value.compareTo(a.value)))
        .map((e) => e.key)
        .take(5)
        .toList();
  }

  static int _countFatigueBlocked(List<CheckIn> checkIns) {
    var count = 0;
    for (final ci in checkIns) {
      final answers = _parseAnswers(ci.answersJson);
      final symptoms = (answers['symptoms'] as List<dynamic>?) ?? [];
      for (final s in symptoms) {
        final sMap = s as Map<String, dynamic>;
        if (sMap['category'] == 'fatigue' && sMap['blocks_daily'] == true) {
          count++;
          break; // count once per session
        }
      }
    }
    return count;
  }

  static Map<String, dynamic> _parseAnswers(String json) {
    try {
      return jsonDecode(json) as Map<String, dynamic>;
    } catch (_) {
      return {};
    }
  }

  static List<TrendPoint> _samplePoints(
    List<TrendPoint> points, {
    required int maxCount,
  }) {
    if (points.length <= maxCount) return points;
    final step = points.length / maxCount;
    return [
      for (var i = 0; i < maxCount; i++) points[(i * step).round().clamp(0, points.length - 1)],
    ];
  }

  static PdfColor _scoreToHeatColor(int? score) {
    if (score == null) return _kGrey300;
    if (score <= 2) return _kDanger;
    if (score <= 4) return PdfColor.fromInt(0xFFFF7043);
    if (score <= 6) return _kWarning;
    if (score <= 8) return _kPrimaryLight;
    return _kSuccess;
  }

  static String _formatCategory(String cat) {
    return switch (cat) {
      'fever' => 'Fever',
      'pain' => 'Pain',
      'fatigue' => 'Fatigue',
      'nausea' => 'Nausea',
      'other' => 'Other',
      _ => _capitalize(cat),
    };
  }

  static String _capitalize(String s) =>
      s.isEmpty ? s : '${s[0].toUpperCase()}${s.substring(1)}';
}

